frr defaults datacenter
hostname gw
ip forwarding
!
interface eth1
 ip address 10.0.1.1/24
interface eth2
 ip address 10.0.2.1/24
interface eth3
 ip address 10.0.3.1/24
interface eth4
 ip address 10.0.4.1/24
interface eth5
 ip address 10.0.5.1/24
interface eth6
 ip address 10.0.6.1/24
interface eth7
 ip address 10.0.7.1/24
interface eth8
 ip address 10.0.8.1/24
!
